package com.hpfxd.polar.util;

import lombok.AllArgsConstructor;
import lombok.Getter;

@AllArgsConstructor
@Getter
public enum Material {
    AIR(-1, "air", "Air", -1),
    STONE(1, "stone", "Stone", 64),
    GRASS(2, "grass", "Grass Block", 64),
    DIRT(3, "dirt", "Dirt", 64),
    COBBLESTONE(4, "cobblestone", "Cobblestone", 64),
    PLANKS(5, "planks", "Wood Planks", 64),
    SAPLING(6, "sapling", "Sapling", 64),
    BEDROCK(7, "bedrock", "Bedrock", 64),
    FLOWING_WATER(8, "flowing_water", "Water", 64),
    WATER(9, "water", "Stationary Water", 64),
    FLOWING_LAVA(10, "flowing_lava", "Lava", 64),
    LAVA(11, "lava", "Stationary Lava", 64),
    SAND(12, "sand", "Sand", 64),
    GRAVEL(13, "gravel", "Gravel", 64),
    GOLD_ORE(14, "gold_ore", "Gold Ore", 64),
    IRON_ORE(15, "iron_ore", "Iron Ore", 64),
    COAL_ORE(16, "coal_ore", "Coal Ore", 64),
    LOG(17, "log", "Wood", 64),
    LEAVES(18, "leaves", "Leaves", 64),
    SPONGE(19, "sponge", "Sponge", 64),
    GLASS(20, "glass", "Glass", 64),
    LAPIS_ORE(21, "lapis_ore", "Lapis Lazuli Ore", 64),
    LAPIS_BLOCK(22, "lapis_block", "Lapis Lazuli Block", 64),
    DISPENSER(23, "dispenser", "Dispenser", 64),
    SANDSTONE(24, "sandstone", "Sandstone", 64),
    NOTEBLOCK(25, "noteblock", "Note Block", 64),
    GOLDEN_RAIL(27, "golden_rail", "Powered Rail", 64),
    DETECTOR_RAIL(28, "detector_rail", "Detector Rail", 64),
    STICKY_PISTON(29, "sticky_piston", "Sticky Piston", 64),
    WEB(30, "web", "Cobweb", 64),
    TALLGRASS(31, "tallgrass", "Grass", 64),
    DEADBUSH(32, "deadbush", "Dead Bush", 64),
    PISTON(33, "piston", "Piston", 64),
    PISTON_HEAD(34, "piston_head", "Piston Head", 64),
    WOOL(35, "wool", "Wool", 64),
    PISTON_EXTENSION(36, "piston_extension", "Block moved by Piston", 64),
    YELLOW_FLOWER(37, "yellow_flower", "Dandelion", 64),
    RED_FLOWER(38, "red_flower", "Poppy", 64),
    BROWN_MUSHROOM(39, "brown_mushroom", "Brown Mushroom", 64),
    RED_MUSHROOM(40, "red_mushroom", "Red Mushroom", 64),
    GOLD_BLOCK(41, "gold_block", "Block of Gold", 64),
    IRON_BLOCK(42, "iron_block", "Block of Iron", 64),
    DOUBLE_STONE_SLAB(43, "double_stone_slab", "Double Stone Slab", 64),
    STONE_SLAB(44, "stone_slab", "Stone Slab", 64),
    BRICK_BLOCK(45, "brick_block", "Bricks", 64),
    TNT(46, "tnt", "TNT", 64),
    BOOKSHELF(47, "bookshelf", "Bookshelf", 64),
    MOSSY_COBBLESTONE(48, "mossy_cobblestone", "Moss Stone", 64),
    OBSIDIAN(49, "obsidian", "Obsidian", 64),
    TORCH(50, "torch", "Torch", 64),
    FIRE(51, "fire", "Fire", 64),
    MOB_SPAWNER(52, "mob_spawner", "Monster Spawner", 64),
    OAK_STAIRS(53, "oak_stairs", "Oak Wood Stairs", 64),
    CHEST(54, "chest", "Chest", 64),
    REDSTONE_WIRE(55, "redstone_wire", "Redstone Wire", 64),
    DIAMOND_ORE(56, "diamond_ore", "Diamond Ore", 64),
    DIAMOND_BLOCK(57, "diamond_block", "Block of Diamond", 64),
    CRAFTING_TABLE(58, "crafting_table", "Crafting Table", 64),
    FARMLAND(60, "farmland", "Farmland", 64),
    FURNACE(61, "furnace", "Furnace", 64),
    LIT_FURNACE(62, "lit_furnace", "Burning Furnace", 64),
    STANDING_SIGN(63, "standing_sign", "Standing Sign", 64),
    LADDER(65, "ladder", "Ladder", 64),
    RAIL(66, "rail", "Rail", 64),
    STONE_STAIRS(67, "stone_stairs", "Cobblestone Stairs", 64),
    WALL_SIGN(68, "wall_sign", "Wall Sign", 64),
    LEVER(69, "lever", "Lever", 64),
    STONE_PRESSURE_PLATE(70, "stone_pressure_plate", "Stone Pressure Plate", 64),
    WOODEN_PRESSURE_PLATE(72, "wooden_pressure_plate", "Wooden Pressure Plate", 64),
    REDSTONE_ORE(73, "redstone_ore", "Redstone Ore", 64),
    LIT_REDSTONE_ORE(74, "lit_redstone_ore", "Glowing Redstone Ore", 64),
    UNLIT_REDSTONE_TORCH(75, "unlit_redstone_torch", "Redstone Torch (inactive)", 64),
    REDSTONE_TORCH(76, "redstone_torch", "Redstone Torch (active)", 64),
    STONE_BUTTON(77, "stone_button", "Stone Button", 64),
    SNOW_LAYER(78, "snow_layer", "Snow (layer)", 64),
    ICE(79, "ice", "Ice", 64),
    SNOW(80, "snow", "Snow", 64),
    CACTUS(81, "cactus", "Cactus", 64),
    CLAY(82, "clay", "Clay", 64),
    JUKEBOX(84, "jukebox", "Jukebox", 64),
    FENCE(85, "fence", "Fence", 64),
    PUMPKIN(86, "pumpkin", "Pumpkin", 64),
    NETHERRACK(87, "netherrack", "Netherrack", 64),
    SOUL_SAND(88, "soul_sand", "Soul Sand", 64),
    GLOWSTONE(89, "glowstone", "Glowstone", 64),
    PORTAL(90, "portal", "Nether Portal", 64),
    LIT_PUMPKIN(91, "lit_pumpkin", "Jack o'Lantern", 64),
    UNPOWERED_REPEATER(93, "unpowered_repeater", "Redstone Repeater (inactive)", 64),
    POWERED_REPEATER(94, "powered_repeater", "Redstone Repeater (active)", 64),
    STAINED_GLASS(95, "stained_glass", "Stained Glass", 64),
    TRAPDOOR(96, "trapdoor", "Trapdoor", 64),
    MONSTER_EGG(97, "monster_egg", "Monster Egg", 64),
    STONEBRICK(98, "stonebrick", "Stone Bricks", 64),
    BROWN_MUSHROOM_BLOCK(99, "brown_mushroom_block", "Brown Mushroom (block)", 64),
    RED_MUSHROOM_BLOCK(100, "red_mushroom_block", "Red Mushroom (block)", 64),
    IRON_BARS(101, "iron_bars", "Iron Bars", 64),
    GLASS_PANE(102, "glass_pane", "Glass Pane", 64),
    MELON_BLOCK(103, "melon_block", "Melon", 64),
    PUMPKIN_STEM(104, "pumpkin_stem", "Pumpkin Stem", 64),
    MELON_STEM(105, "melon_stem", "Melon Stem", 64),
    VINE(106, "vine", "Vines", 64),
    FENCE_GATE(107, "fence_gate", "Fence Gate", 64),
    BRICK_STAIRS(108, "brick_stairs", "Brick Stairs", 64),
    STONE_BRICK_STAIRS(109, "stone_brick_stairs", "Stone Brick Stairs", 64),
    MYCELIUM(110, "mycelium", "Mycelium", 64),
    WATERLILY(111, "waterlily", "Lily Pad", 64),
    NETHER_BRICK(112, "nether_brick", "Nether Brick", 64),
    NETHER_BRICK_FENCE(113, "nether_brick_fence", "Nether Brick Fence", 64),
    NETHER_BRICK_STAIRS(114, "nether_brick_stairs", "Nether Brick Stairs", 64),
    ENCHANTING_TABLE(116, "enchanting_table", "Enchantment Table", 64),
    END_PORTAL(119, "end_portal", "End Portal", 64),
    END_PORTAL_FRAME(120, "end_portal_frame", "End Portal Block", 64),
    END_STONE(121, "end_stone", "End Stone", 64),
    DRAGON_EGG(122, "dragon_egg", "Dragon Egg", 64),
    REDSTONE_LAMP(123, "redstone_lamp", "Redstone Lamp (inactive)", 64),
    LIT_REDSTONE_LAMP(124, "lit_redstone_lamp", "Redstone Lamp (active)", 64),
    DOUBLE_WOODEN_SLAB(125, "double_wooden_slab", "Double Wooden Slab", 64),
    WOODEN_SLAB(126, "wooden_slab", "Wooden Slab", 64),
    COCOA(127, "cocoa", "Cocoa", 64),
    SANDSTONE_STAIRS(128, "sandstone_stairs", "Sandstone Stairs", 64),
    EMERALD_ORE(129, "emerald_ore", "Emerald Ore", 64),
    ENDER_CHEST(130, "ender_chest", "Ender Chest", 64),
    TRIPWIRE_HOOK(131, "tripwire_hook", "Tripwire Hook", 64),
    TRIPWIRE(132, "tripwire", "Tripwire", 64),
    EMERALD_BLOCK(133, "emerald_block", "Block of Emerald", 64),
    SPRUCE_STAIRS(134, "spruce_stairs", "Spruce Wood Stairs", 64),
    BIRCH_STAIRS(135, "birch_stairs", "Birch Wood Stairs", 64),
    JUNGLE_STAIRS(136, "jungle_stairs", "Jungle Wood Stairs", 64),
    COMMAND_BLOCK(137, "command_block", "Command Block", 64),
    BEACON(138, "beacon", "Beacon", 64),
    COBBLESTONE_WALL(139, "cobblestone_wall", "Cobblestone Wall", 64),
    CARROTS(141, "carrots", "Carrot", 64),
    POTATOES(142, "potatoes", "Potato", 64),
    WOODEN_BUTTON(143, "wooden_button", "Wooden Button", 64),
    ANVIL(145, "anvil", "Anvil", 64),
    TRAPPED_CHEST(146, "trapped_chest", "Trapped Chest", 64),
    LIGHT_WEIGHTED_PRESSURE_PLATE(147, "light_weighted_pressure_plate", "Weighted Pressure Plate (Light)", 64),
    HEAVY_WEIGHTED_PRESSURE_PLATE(148, "heavy_weighted_pressure_plate", "Weighted Pressure Plate (Heavy)", 64),
    UNPOWERED_COMPARATOR(149, "unpowered_comparator", "Redstone Comparator", 64),
    POWERED_COMPARATOR(150, "powered_comparator", "Redstone Comparator (deprecated)", 64),
    DAYLIGHT_DETECTOR(151, "daylight_detector", "Daylight Sensor", 64),
    REDSTONE_BLOCK(152, "redstone_block", "Block of Redstone", 64),
    QUARTZ_ORE(153, "quartz_ore", "Nether Quartz Ore", 64),
    HOPPER(154, "hopper", "Hopper", 64),
    QUARTZ_BLOCK(155, "quartz_block", "Block of Quartz", 64),
    QUARTZ_STAIRS(156, "quartz_stairs", "Quartz Stairs", 64),
    ACTIVATOR_RAIL(157, "activator_rail", "Activator Rail", 64),
    DROPPER(158, "dropper", "Dropper", 64),
    STAINED_HARDENED_CLAY(159, "stained_hardened_clay", "Stained Clay", 64),
    STAINED_GLASS_PANE(160, "stained_glass_pane", "Stained Glass Pane", 64),
    LEAVES2(161, "leaves2", "Leaves (Acacia/Dark Oak)", 64),
    LOG2(162, "log2", "Wood (Acacia/Dark Oak)", 64),
    ACACIA_STAIRS(163, "acacia_stairs", "Acacia Wood Stairs", 64),
    DARK_OAK_STAIRS(164, "dark_oak_stairs", "Dark Oak Wood Stairs", 64),
    SLIME(165, "slime", "Slime Block", 64),
    BARRIER(166, "barrier", "Barrier", 64),
    IRON_TRAPDOOR(167, "iron_trapdoor", "Iron Trapdoor", 64),
    PRISMARINE(168, "prismarine", "Prismarine", 64),
    SEA_LANTERN(169, "sea_lantern", "Sea Lantern", 64),
    HAY_BLOCK(170, "hay_block", "Hay Bale", 64),
    CARPET(171, "carpet", "Carpet", 64),
    HARDENED_CLAY(172, "hardened_clay", "Hardened Clay", 64),
    COAL_BLOCK(173, "coal_block", "Block of Coal", 64),
    PACKED_ICE(174, "packed_ice", "Packed Ice", 64),
    DOUBLE_PLANT(175, "double_plant", "Large Flowers", 64),
    STANDING_BANNER(176, "standing_banner", "Standing Banner", 64),
    WALL_BANNER(177, "wall_banner", "Wall Banner", 64),
    DAYLIGHT_DETECTOR_INVERTED(178, "daylight_detector_inverted", "Inverted Daylight Sensor", 64),
    RED_SANDSTONE(179, "red_sandstone", "Red Sandstone", 64),
    RED_SANDSTONE_STAIRS(180, "red_sandstone_stairs", "Red Sandstone Stairs", 64),
    DOUBLE_STONE_SLAB2(181, "double_stone_slab2", "Double Red Sandstone Slab", 64),
    STONE_SLAB2(182, "stone_slab2", "Red Sandstone Slab", 64),
    SPRUCE_FENCE_GATE(183, "spruce_fence_gate", "Spruce Fence Gate", 64),
    BIRCH_FENCE_GATE(184, "birch_fence_gate", "Birch Fence Gate", 64),
    JUNGLE_FENCE_GATE(185, "jungle_fence_gate", "Jungle Fence Gate", 64),
    DARK_OAK_FENCE_GATE(186, "dark_oak_fence_gate", "Dark Oak Fence Gate", 64),
    ACACIA_FENCE_GATE(187, "acacia_fence_gate", "Acacia Fence Gate", 64),
    SPRUCE_FENCE(188, "spruce_fence", "Spruce Fence", 64),
    BIRCH_FENCE(189, "birch_fence", "Birch Fence", 64),
    JUNGLE_FENCE(190, "jungle_fence", "Jungle Fence", 64),
    DARK_OAK_FENCE(191, "dark_oak_fence", "Dark Oak Fence", 64),
    ACACIA_FENCE(192, "acacia_fence", "Acacia Fence", 64),
    IRON_SHOVEL(256, "iron_shovel", "Iron Shovel", 1),
    IRON_PICKAXE(257, "iron_pickaxe", "Iron Pickaxe", 1),
    IRON_AXE(258, "iron_axe", "Iron Axe", 1),
    FLINT_AND_STEEL(259, "flint_and_steel", "Flint and Steel", 1),
    APPLE(260, "apple", "Apple", 64),
    BOW(261, "bow", "Bow", 1),
    ARROW(262, "arrow", "Arrow", 64),
    COAL(263, "coal", "Coal", 64),
    DIAMOND(264, "diamond", "Diamond", 64),
    IRON_INGOT(265, "iron_ingot", "Iron Ingot", 64),
    GOLD_INGOT(266, "gold_ingot", "Gold Ingot", 64),
    IRON_SWORD(267, "iron_sword", "Iron Sword", 1),
    WOODEN_SWORD(268, "wooden_sword", "Wooden Sword", 1),
    WOODEN_SHOVEL(269, "wooden_shovel", "Wooden Shovel", 1),
    WOODEN_PICKAXE(270, "wooden_pickaxe", "Wooden Pickaxe", 1),
    WOODEN_AXE(271, "wooden_axe", "Wooden Axe", 1),
    STONE_SWORD(272, "stone_sword", "Stone Sword", 1),
    STONE_SHOVEL(273, "stone_shovel", "Stone Shovel", 1),
    STONE_PICKAXE(274, "stone_pickaxe", "Stone Pickaxe", 1),
    STONE_AXE(275, "stone_axe", "Stone Axe", 1),
    DIAMOND_SWORD(276, "diamond_sword", "Diamond Sword", 1),
    DIAMOND_SHOVEL(277, "diamond_shovel", "Diamond Shovel", 1),
    DIAMOND_PICKAXE(278, "diamond_pickaxe", "Diamond Pickaxe", 1),
    DIAMOND_AXE(279, "diamond_axe", "Diamond Axe", 1),
    STICK(280, "stick", "Stick", 64),
    BOWL(281, "bowl", "Bowl", 64),
    MUSHROOM_STEW(282, "mushroom_stew", "Mushroom Stew", 1),
    GOLDEN_SWORD(283, "golden_sword", "Golden Sword", 1),
    GOLDEN_SHOVEL(284, "golden_shovel", "Golden Shovel", 1),
    GOLDEN_PICKAXE(285, "golden_pickaxe", "Golden Pickaxe", 1),
    GOLDEN_AXE(286, "golden_axe", "Golden Axe", 1),
    STRING(287, "string", "String", 64),
    FEATHER(288, "feather", "Feather", 64),
    GUNPOWDER(289, "gunpowder", "Gunpowder", 64),
    WOODEN_HOE(290, "wooden_hoe", "Wooden Hoe", 1),
    STONE_HOE(291, "stone_hoe", "Stone Hoe", 1),
    IRON_HOE(292, "iron_hoe", "Iron Hoe", 1),
    DIAMOND_HOE(293, "diamond_hoe", "Diamond Hoe", 1),
    GOLDEN_HOE(294, "golden_hoe", "Golden Hoe", 1),
    WHEAT_SEEDS(295, "wheat_seeds", "Seeds", 64),
    WHEAT(296, "wheat", "Wheat", 64),
    BREAD(297, "bread", "Bread", 64),
    LEATHER_HELMET(298, "leather_helmet", "Leather Cap", 1),
    LEATHER_CHESTPLATE(299, "leather_chestplate", "Leather Tunic", 1),
    LEATHER_LEGGINGS(300, "leather_leggings", "Leather Pants", 1),
    LEATHER_BOOTS(301, "leather_boots", "Leather Boots", 1),
    CHAINMAIL_HELMET(302, "chainmail_helmet", "Chain Helmet", 1),
    CHAINMAIL_CHESTPLATE(303, "chainmail_chestplate", "Chain Chestplate", 1),
    CHAINMAIL_LEGGINGS(304, "chainmail_leggings", "Chain Leggings", 1),
    CHAINMAIL_BOOTS(305, "chainmail_boots", "Chain Boots", 1),
    IRON_HELMET(306, "iron_helmet", "Iron Helmet", 1),
    IRON_CHESTPLATE(307, "iron_chestplate", "Iron Chestplate", 1),
    IRON_LEGGINGS(308, "iron_leggings", "Iron Leggings", 1),
    IRON_BOOTS(309, "iron_boots", "Iron Boots", 1),
    DIAMOND_HELMET(310, "diamond_helmet", "Diamond Helmet", 1),
    DIAMOND_CHESTPLATE(311, "diamond_chestplate", "Diamond Chestplate", 1),
    DIAMOND_LEGGINGS(312, "diamond_leggings", "Diamond Leggings", 1),
    DIAMOND_BOOTS(313, "diamond_boots", "Diamond Boots", 1),
    GOLDEN_HELMET(314, "golden_helmet", "Golden Helmet", 1),
    GOLDEN_CHESTPLATE(315, "golden_chestplate", "Golden Chestplate", 1),
    GOLDEN_LEGGINGS(316, "golden_leggings", "Golden Leggings", 1),
    GOLDEN_BOOTS(317, "golden_boots", "Golden Boots", 1),
    FLINT(318, "flint", "Flint", 64),
    PORKCHOP(319, "porkchop", "Raw Porkchop", 64),
    COOKED_PORKCHOP(320, "cooked_porkchop", "Cooked Porkchop", 64),
    PAINTING(321, "painting", "Painting", 64),
    GOLDEN_APPLE(322, "golden_apple", "Golden Apple", 64),
    SIGN(323, "sign", "Sign", 16),
    WOODEN_DOOR(324, "wooden_door", "Oak Door", 64),
    BUCKET(325, "bucket", "Bucket", 16),
    WATER_BUCKET(326, "water_bucket", "Water Bucket", 64),
    LAVA_BUCKET(327, "lava_bucket", "Lava Bucket", 64),
    MINECART(328, "minecart", "Minecart", 1),
    SADDLE(329, "saddle", "Saddle", 1),
    IRON_DOOR(330, "iron_door", "Iron Door", 64),
    REDSTONE(331, "redstone", "Redstone", 64),
    SNOWBALL(332, "snowball", "Snowball", 16),
    BOAT(333, "boat", "Boat", 1),
    LEATHER(334, "leather", "Leather", 64),
    MILK_BUCKET(335, "milk_bucket", "Milk", 1),
    BRICK(336, "brick", "Brick", 64),
    CLAY_BALL(337, "clay_ball", "Clay", 64),
    REEDS(338, "reeds", "Sugar Cane", 64),
    PAPER(339, "paper", "Paper", 64),
    BOOK(340, "book", "Book", 64),
    SLIME_BALL(341, "slime_ball", "Slimeball", 64),
    CHEST_MINECART(342, "chest_minecart", "Minecart with Chest", 1),
    FURNACE_MINECART(343, "furnace_minecart", "Minecart with Furnace", 1),
    EGG(344, "egg", "Egg", 16),
    COMPASS(345, "compass", "Compass", 64),
    FISHING_ROD(346, "fishing_rod", "Fishing Rod", 1),
    CLOCK(347, "clock", "Clock", 64),
    GLOWSTONE_DUST(348, "glowstone_dust", "Glowstone Dust", 64),
    FISH(349, "fish", "Raw Fish", 64),
    COOKED_FISH(350, "cooked_fish", "Cooked Fish", 64),
    DYE(351, "dye", "Dye", 64),
    BONE(352, "bone", "Bone", 64),
    SUGAR(353, "sugar", "Sugar", 64),
    CAKE(354, "cake", "Cake", 1),
    BED(355, "bed", "Bed", 1),
    REPEATER(356, "repeater", "Redstone Repeater", 64),
    COOKIE(357, "cookie", "Cookie", 64),
    FILLED_MAP(358, "filled_map", "Map", 64),
    SHEARS(359, "shears", "Shears", 1),
    MELON(360, "melon", "Melon", 64),
    PUMPKIN_SEEDS(361, "pumpkin_seeds", "Pumpkin Seeds", 64),
    MELON_SEEDS(362, "melon_seeds", "Melon Seeds", 64),
    BEEF(363, "beef", "Raw Beef", 64),
    COOKED_BEEF(364, "cooked_beef", "Steak", 64),
    CHICKEN(365, "chicken", "Raw Chicken", 64),
    COOKED_CHICKEN(366, "cooked_chicken", "Cooked Chicken", 64),
    ROTTEN_FLESH(367, "rotten_flesh", "Rotten Flesh", 64),
    ENDER_PEARL(368, "ender_pearl", "Ender Pearl", 16),
    BLAZE_ROD(369, "blaze_rod", "Blaze Rod", 64),
    GHAST_TEAR(370, "ghast_tear", "Ghast Tear", 64),
    GOLD_NUGGET(371, "gold_nugget", "Gold Nugget", 64),
    NETHER_WART(372, "nether_wart", "Nether Wart", 64),
    POTION(373, "potion", "Potion", 1),
    GLASS_BOTTLE(374, "glass_bottle", "Glass Bottle", 64),
    SPIDER_EYE(375, "spider_eye", "Spider Eye", 64),
    FERMENTED_SPIDER_EYE(376, "fermented_spider_eye", "Fermented Spider Eye", 64),
    BLAZE_POWDER(377, "blaze_powder", "Blaze Powder", 64),
    MAGMA_CREAM(378, "magma_cream", "Magma Cream", 64),
    BREWING_STAND(379, "brewing_stand", "Brewing Stand", 64),
    CAULDRON(380, "cauldron", "Cauldron", 64),
    ENDER_EYE(381, "ender_eye", "Eye of Ender", 64),
    SPECKLED_MELON(382, "speckled_melon", "Glistering Melon", 64),
    SPAWN_EGG(383, "spawn_egg", "Spawn Egg", 64),
    EXPERIENCE_BOTTLE(384, "experience_bottle", "Bottle o' Enchanting", 64),
    FIRE_CHARGE(385, "fire_charge", "Fire Charge", 64),
    WRITABLE_BOOK(386, "writable_book", "Book and Quill", 1),
    WRITTEN_BOOK(387, "written_book", "Written Book", 16),
    EMERALD(388, "emerald", "Emerald", 64),
    ITEM_FRAME(389, "item_frame", "Item Frame", 64),
    FLOWER_POT(390, "flower_pot", "Flower Pot", 64),
    CARROT(391, "carrot", "Carrot", 64),
    POTATO(392, "potato", "Potato", 64),
    BAKED_POTATO(393, "baked_potato", "Baked Potato", 64),
    POISONOUS_POTATO(394, "poisonous_potato", "Poisonous Potato", 64),
    MAP(395, "map", "Empty Map", 64),
    GOLDEN_CARROT(396, "golden_carrot", "Golden Carrot", 64),
    SKULL(397, "skull", "Mob head", 64),
    CARROT_ON_A_STICK(398, "carrot_on_a_stick", "Carrot on a Stick", 1),
    NETHER_STAR(399, "nether_star", "Nether Star", 64),
    PUMPKIN_PIE(400, "pumpkin_pie", "Pumpkin Pie", 64),
    FIREWORKS(401, "fireworks", "Firework Rocket", 64),
    FIREWORK_CHARGE(402, "firework_charge", "Firework Star", 64),
    ENCHANTED_BOOK(403, "enchanted_book", "Enchanted Book", 1),
    COMPARATOR(404, "comparator", "Redstone Comparator", 64),
    NETHERBRICK(405, "netherbrick", "Nether Brick", 64),
    QUARTZ(406, "quartz", "Nether Quartz", 64),
    TNT_MINECART(407, "tnt_minecart", "Minecart with TNT", 1),
    HOPPER_MINECART(408, "hopper_minecart", "Minecart with Hopper", 1),
    PRISMARINE_SHARD(409, "prismarine_shard", "Prismarine Shard", 64),
    PRISMARINE_CRYSTALS(410, "prismarine_crystals", "Prismarine Crystals", 64),
    RABBIT(411, "rabbit", "Raw Rabbit", 64),
    COOKED_RABBIT(412, "cooked_rabbit", "Cooked Rabbit", 64),
    RABBIT_STEW(413, "rabbit_stew", "Rabbit Stew", 1),
    RABBIT_FOOT(414, "rabbit_foot", "Rabbit's Foot", 64),
    RABBIT_HIDE(415, "rabbit_hide", "Rabbit Hide", 64),
    ARMOR_STAND(416, "armor_stand", "Armor Stand", 16),
    IRON_HORSE_ARMOR(417, "iron_horse_armor", "Iron Horse Armor", 1),
    GOLDEN_HORSE_ARMOR(418, "golden_horse_armor", "Golden Horse Armor", 1),
    DIAMOND_HORSE_ARMOR(419, "diamond_horse_armor", "Diamond Horse Armor", 1),
    LEAD(420, "lead", "Lead", 64),
    NAME_TAG(421, "name_tag", "Name Tag", 64),
    COMMAND_BLOCK_MINECART(422, "command_block_minecart", "Minecart with Command Block", 1),
    MUTTON(423, "mutton", "Raw Mutton", 64),
    COOKED_MUTTON(424, "cooked_mutton", "Cooked Mutton", 64),
    BANNER(425, "banner", "Banner", 16),
    SPRUCE_DOOR(427, "spruce_door", "Spruce Door", 64),
    BIRCH_DOOR(428, "birch_door", "Birch Door", 64),
    JUNGLE_DOOR(429, "jungle_door", "Jungle Door", 64),
    ACACIA_DOOR(430, "acacia_door", "Acacia Door", 64),
    DARK_OAK_DOOR(431, "dark_oak_door", "Dark Oak Door", 64),
    RECORD_13(2256, "record_13", "13 Disc", 1),
    RECORD_CAT(2257, "record_cat", "Cat Disc", 1),
    RECORD_BLOCKS(2258, "record_blocks", "Blocks Disc", 1),
    RECORD_CHIRP(2259, "record_chirp", "Chirp Disc", 1),
    RECORD_FAR(2260, "record_far", "Far Disc", 1),
    RECORD_MALL(2261, "record_mall", "Mall Disc", 1),
    RECORD_MELLOHI(2262, "record_mellohi", "Mellohi Disc", 1),
    RECORD_STAL(2263, "record_stal", "Stal Disc", 1),
    RECORD_STRAD(2264, "record_strad", "Strad Disc", 1),
    RECORD_WARD(2265, "record_ward", "Ward Disc", 1),
    RECORD_11(2266, "record_11", "11 Disc", 1),
    RECORD_WAIT(2267, "record_wait", "Wait Disc", 1)
    ;
    private final int id;
    private final String name;
    private final String displayName;
    private final int maxStackSize;

    public boolean isSword() {
        return this.name.endsWith("_sword");
    }
}
